name: pizza_order_app
description: Um aplicativo para pedidos de pizza.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^10.0.0
  flutter_map: ^6.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/pizza_banner.png
  - assets/margherita.png
  - assets/pepperoni.png
  - assets/quatro_queijos.png